### ISSUE TITLE
ACsGuis Download Server

### ISSUE THREAD

**Issue by gameusefly** [DynamXInc/DynamX#11]
**Describe the bug**
The newest AcsGuis jar isnt on web for download

**To Reproduce**
1. start newest dynamx or go to https://dynamx.fr/download/libs/ACsGuis-1.2.4-1-all.jar
2. see dynamx crash because he cannot download acsguis

**Expected behavior**
DynamX will download the newest AcsGuis and start my game :(

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Additional context**
It would be nice to change the acsguis url in the beta branche to https://maven.dynamx.fr/ui/native/ACsGuisRepo/fr/aym/acsguis/ACsGuis/[version] to avoid the problems, for releases it could be the dynamx libs website

**Comment by AymericBdy** [comment]
Thanks for your issue and your idea of solution.
Implemented in https://github.com/DynamXInc/DynamX/commit/d4852a3c0926b39321cf3f34dd18274ee4516639

**Comment by gameusefly** [comment]
hey, i guess the maven download server is not the way to go 😅 
since the change he download somthing but only 3kb of size (i guess the website content or something?)
on self downloading (https://maven.dynamx.fr/ui/native/ACsGuisRepo/fr/aym/acsguis/ACsGuis/1.2.4-4/ACsGuis-1.2.4-4.jar) it delay a second before it download the jar, this could be the issue
