### ISSUE TITLE
ACsService is still needed

### ISSUE THREAD

**Issue by gameusefly** [DynamXInc/DynamX#12]
**Describe the bug**
Since some commit the ACsService interface was removed. In the Docs of the class is written "Required here in DynamX because of the coremod loading system :c" though it was removed.

**To Reproduce**
1. Build DynamX (beta branche)
2. start
3. crash

**Expected behavior**
My game start

**Desktop (please complete the following information):**
 - OS: windows

**Comment by AymericBdy** [comment]
Issue fixed, you're right. Thanks for the issue :)
