### ISSUE TITLE
MPS broke Models

### ISSUE THREAD

**Issue by gameusefly** [DynamXInc/DynamX#24]
**Describe the bug**
Since the Commit "Update MPS", Models from Packs (for example BasicPack) cannot load and there appear "Error" Vehicles everywhere

**To Reproduce**
1. Start newest DynamX with commit "Update MPS" & BasicPack
2. Spawn Car
3. See Error Vehicle

**Expected behavior**
Beautiful Car Models form Dartcher 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Newest

Extra comment
I reverted the commit on my personal fork and the issue not there anymore

**Comment by AymericBdy** [comment]
We are reworking the way DynamX packs are loaded (in link with a software to create protected packs), so the issue may stay a few days. 
I advise you to keep the solution of reverting the commit.

Thanks for your report.

**Comment by AymericBdy** [comment]
Edit: already fixed
