### ISSUE TITLE
DnxChunks region files are used across worlds

### ISSUE THREAD

**Issue by JarException** [DynamXInc/DynamX#28]
**Describe the bug**
DnxChunks region files are used across worlds somehow

**To Reproduce**
1. go to a new map in singleplayer
2. activate the client debug renderer to see terrain blocks
3. spawn props
4. write down the coordinates
5. go to a new singeplayer world
6. teleport to the coordinates
7. spawn props
8. search for blue terrain in the air where no blocks are located

**DynamX version**
latest beta branch

**Expected behavior**
The props should adapt to the terrain of the new world and not to that of the old one

**Comment by AymericBdy** [comment]
Fixed in commit https://github.com/DynamXInc/DynamX/commit/efc71febe97be3edd20fdc8de591d2cd8dad5c9d
