### ISSUE TITLE
Models register manuellement via DynamXModelRegistry.registerModel() ne sont pas register

### ISSUE THREAD

**Issue by BlackNiteHD** [DynamXInc/DynamX#33]
Tout model register manuellement via DynamXModelRegistry.registerModel() n'est pas register car il est clear avant dans la méthode `onPackInfosReloaded()` de `DynamXModelRegistry`

**Comment by AymericBdy** [comment]
Fixé dans le commit https://github.com/DynamXInc/DynamX/commit/f7bfea412ed2172fa45f959cfa2934ff5764fad4
J'ai aussi clean les fonctions pour register manuellement des modèles.
