### ISSUE TITLE
White box that appears randomly

### ISSUE THREAD

**Issue by raphaelcolau** [DynamXInc/DynamX#34]
**Describe the bug**
White box that appears randomly on all models (it appears when the game is launched and does not disappear until the game is restarted)

**To Reproduce**
1. Launch the game several times and the bug will appear

**Screenshots**
![image](https://user-images.githubusercontent.com/48066106/221262988-880426dc-391c-40ad-a735-9d025cf7ff9e.png)

**Mods:**
 - Forge 2860
 - Version DynamX-4.0.0-beta-15e-all

**Additional context**
mps: HTTP (not S) localhost

**Comment by AymericBdy** [comment]
This is due to an ambiguous naming of your collision shape "Shape_light" (recognized as a light by DynamX).

Closing this issue as this is due to a different problem with DynamX (how it handles ambiguous config names).
