### ISSUE TITLE
Collision avec item drop inexistant / Non-existent collision with dropped items

### ISSUE THREAD

**Issue by Proxome** [DynamXInc/DynamX#35]
> __Bug report :__ [Français]

Lors du drop d'un item, celui-ci passe à travers les collisions des blocs importer par Dynamx (*vidéo 1*).

[https://youtu.be/Kpu2b4ZkSkE](url) (*vidéo 1*)

> __Bug report :__ [English]

When dropping an item, it passes through the collisions of the blocks imported on Dynamx (*video 1*).

[https://youtu.be/Kpu2b4ZkSkE](url) (*video 1*)

**Comment by AymericBdy** [comment]
Bug solved in https://github.com/DynamXInc/DynamX/commit/f0c2169ac30835a286022d71e8e3314cdf76f321
Thanks for the report.
