### ISSUE TITLE
Possible perte de performance liée à DynamX / Possible performance loss linked to DynamX 

### ISSUE THREAD

**Issue by Proxome** [DynamXInc/DynamX#36]
>__Bug report :__ [Français]

Perte de performance en jeu à intervalle régulier, en mouvement ou même statique (*vidéo1*). Le mod étant uniquement utilisé avec le mod **OptiFine_1.12.2_HD_U_G5** sous **Forge-14.23.5.2859** en **1.12.2** (*image 1*).

https://youtu.be/DGYrGiC2ysg (*vidéo 1*)
https://rb.gy/moc4ve (*image 1*)

>__Bug report :__ [English]

Performance loss occurs at regular intervals, whether in motion or static (*video1*). The mod is only used with the **OptiFine_1.12.2_HD_U_G5** mod under **Forge-14.23.5.2859** in **1.12.2** (*image 1*).

https://youtu.be/DGYrGiC2ysg (*vidéo 1*)
https://rb.gy/moc4ve (*image 1*)

**Comment by AymericBdy** [comment]
Closing as this bug comes from the usage of Optifine and Windows.
