### ISSUE TITLE
Encrypted Packs are not loaded correctly at first startup

### ISSUE THREAD

**Issue by JarException** [DynamXInc/DynamX#37]
**Describe the bug**
Encrypted DynamX Packs are not loaded correctly at first startup. 
The obj file is not found at the first startup.

**To Reproduce**
1. Start DynamX with a encrypted Pack
2. Take a look at the vehicles in Singleplayer
3. Check the DynamX Debug menu

**Expected behavior**
Packs should be loaded correctly on first startup

**Version**
 - 4.0.0

**Additional context**
If you close the game afterwards and start it again everything always works

**Exception**
java.lang.RuntimeException: Model Model dynamxmod:models/obj/bmw_m4/m4-statemc.obj in pack DartcherPack cannot be loaded ! java.io.FileNotFoundException: dynamxmod:models/obj/bmw_m4/m4-statemc.obj Has secure loader: true
fr.dynamx.common.objloader.data.ObjModelData.<init>(ObjModelData.java:48)
fr.dynamx.common.DynamXContext.getObjModelDataFromCache(DynamXContext.java:138)
fr.dynamx.client.renders.model.renderer.ObjModelRenderer.loadObjModel(ObjModelRenderer.java:78)
fr.dynamx.client.DynamXModelRegistry.lambda$null$0(DynamXModelRegistry.java:163)
fr.dynamx.client.DynamXModelRegistry$$Lambda$509/2133753354.call(Unknown Source)

**Comment by AymericBdy** [comment]
I tried a few times but I failed to reproduce the bug (with version beta-16).
Can you send me the complete log and the used pack in private ?
Also, what do you mean by "first startup" ? You delete ACsGuis and the bullet library ?

**Comment by AymericBdy** [comment]
This issue was fixed in the latest versions of DynamX (4.0.0 beta > 20).
