### ISSUE TITLE
Collision problem when block is translated

### ISSUE THREAD

**Issue by ThibaultVDY** [DynamXInc/DynamX#40]
Collisions boxes are not updating when you're translating the block.
 Using DynamX 4.0.0-beta-17
![2023-03-13_23 05 15](https://user-images.githubusercontent.com/57434478/224842905-5a416377-a453-420a-afa3-c5a3bd363b77.png)
![2023-03-13_23 05 20](https://user-images.githubusercontent.com/57434478/224842908-a6f6ecab-0a50-47ec-bcbe-5270a1479966.png)
![2023-03-13_23 05 13](https://user-images.githubusercontent.com/57434478/224842909-d6043d45-b497-4925-ab5f-30eb6850485e.png)

**Comment by ThibaultVDY** [comment]
Rotated collisions boxes work but not scale or translation

**Comment by AymericBdy** [comment]
@ThibaultVDY 
Can you re-test with DynamX-beta-18, and send the config of your block plus your log file if it still bugs ?
I didn't manage to reproduce the bug in this version.

**Comment by ThibaultVDY** [comment]
![2023-05-01_23 05 57](https://user-images.githubusercontent.com/57434478/235531781-ebeeee2e-9199-45fb-a3bb-12df2cac25a4.png)
![2023-05-01_23 06 25](https://user-images.githubusercontent.com/57434478/235531783-bd716c17-9085-47de-a2db-aab9df35c760.png)
![2023-05-01_23 08 10](https://user-images.githubusercontent.com/57434478/235531785-1cc85dfc-e5c2-4649-a018-8b5298987b7e.png)
![2023-05-01_23 08 38](https://user-images.githubusercontent.com/57434478/235531788-79bfe626-e2c0-466a-b4c6-861a69ebbbbc.png)

It's just a block extends DynamXBlock, pretty hard to find the block after translating it

[latest.log](https://github.com/DynamXInc/DynamX/files/11368056/latest.log)

**Comment by AymericBdy** [comment]
Hello, the bug will be fixed in DynamX 4.0.0 beta-27, thanks for the report !
