### ISSUE TITLE
Incompatibility with DynamicSurroundings - Incompatibilité avec DynamicSurroundings

### ISSUE THREAD

**Issue by MRavensWood** [DynamXInc/DynamX#41]
Bonjour, la version classique de DynamX était autrefois compatible avec le mod **DynamicSurroundings** mais ne l'est désormais plus avec cette version beta test. 

Il s'agit d'un mod qui rajoute des sons d'ambiance au jeu ce qui est je trouve très utile pour un serveur rp réaliste.

Je sais que cette demande ne sera pas mis dans vos priorités _(à moins qu'elle ne soit très demandé)_ mais je tenait tout de même à vous l'informer.

Merci.

**-----------------------------------------------------------------------------------------**
**-----------------------------------------------------------------------------------------**

Hello, the classic version of DynamX was formerly compatible with the **DynamicSurroundings** mod but is no longer compatible with this beta test version.

This is a mod that adds ambient sounds to the game which I find very useful for a realistic server rp.

I know that this request will not be put in your priorities _(exept if its very requested)_ but i wanted to inform you.

Thanks.

**Comment by AymericBdy** [comment]
Hello,
I found that DynamicSurroundings uses an old version of the Mixins (a dependency of both DynamX and DynamicSurroundings), not compatible with DynamX. 

The solution is to open the DynamicSurroundings jar file with a program like WinRAR (jar files have the same format as zip files), go into the 'org' folder and delete the 'spongepowered' folder. This will allow you to use DynamicSurroundings with DynamX (but if you remove DynamX, your modifier jar of DynamicSurroundings will not work).

Thanks for your report.
