### ISSUE TITLE
Large hitboxes on blocks do not work

### ISSUE THREAD

**Issue by JarException** [DynamXInc/DynamX#47]
**Describe the bug**
If a block larger than 3 blocks is placed, you can simply walk through the positions further away than 3 blocks and then also walk completely through the hitbox.

**To Reproduce**
1. Place a Large Block
2. Walk through

**Expected behavior**
Hitboxes should work on large blocks too

**Version**
 - 4.0.0

**Comment by AymericBdy** [comment]
Hello,
The block collision radius is managed by the 'BlockCollisionRadius2' configuration property (in the dynamxmod.cfg file), and its default value is 3. You can increase it, but you may lose in game performance.
(See https://github.com/DynamXInc/DynamX/blob/beta/src/main/java/fr/dynamx/utils/DynamXConfig.java#L61C44-L61C65).
