### ISSUE TITLE
Update to newest DynamX

### ISSUE THREAD

**Issue by gameusefly** [DynamXInc/DynamX#51]
**Is your feature request related to a problem? Please describe.**
With the newest version of DynamX BasicsAddon doesn't work

**Describe the solution you'd like**
Update DynamX as dependency and fix breaking changes

**Comment by AymericBdy** [comment]
If I understand the issue, it should be on the DynamXAddon's git, no ? @gameusefly

**Comment by gameusefly** [comment]
Oh
