### ISSUE TITLE
Door position problem during entity respawn

### ISSUE THREAD

**Issue by raphaelcolau** [DynamXInc/DynamX#54]
When an entity is spawned and you leave the chunks (chunks are no longer displayed) and when you render the chunk with the vehicle, the doors are no longer restored.

**Comment by AymericBdy** [comment]
With what exact version of DynamX are you having this issue @raphaelcolau (since I fixed it a few weeks ago) ?

**Comment by raphaelcolau** [comment]
> With what exact version of DynamX are you having this issue @raphaelcolau (since I fixed it a few weeks ago) ?

DynamX-4.0.2-dev6 (A version compiled by Yanis so most likely he didn't pull)

**Comment by raphaelcolau** [comment]
Fixed in version 4.1.0
